"""
B2 ORB ML Pipeline Orchestrator — Stages 5→7
Trains B2 model on ml_orb_dataset.parquet (already generated by labels_orb.py).
Saves artifacts as orb_filter_b2.pkl / selected_features_b2.txt / best_params_b2.json.

Usage:
  python scripts/run_orb_pipeline_b2.py              # Run stages 5, 6, 7
  python scripts/run_orb_pipeline_b2.py --from-stage 6  # Re-run from stage 6
  python scripts/run_orb_pipeline_b2.py --trials 500    # More Optuna trials
"""
import sys, shutil
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
sys.stdout.reconfigure(encoding="utf-8")

ROOT        = Path(__file__).parent.parent
DATA_DIR    = ROOT / "data" / "historical" / "ml"
RESULTS_ORB = ROOT / "optimizer" / "results_orb"
DATASET     = DATA_DIR / "ml_orb_dataset.parquet"


def stage5_train():
    print("\n=== Stage 5: 訓練 B2 模型 ===")
    from optimizer.ml.models import train_and_eval
    model, feats = train_and_eval(
        dataset_path=DATASET,
        results_dir=RESULTS_ORB,
        test_start="2025-07-01",
        use_cv=True,
    )
    # Rename output files → b2 suffix (coexist with b1)
    for src, dst in [
        ("breakout_filter.pkl",   "orb_filter_b2.pkl"),
        ("selected_features.txt", "selected_features_b2.txt"),
        ("feature_importance.csv","feature_importance_b2.csv"),
    ]:
        src_p = RESULTS_ORB / src
        dst_p = RESULTS_ORB / dst
        if src_p.exists():
            shutil.copy2(src_p, dst_p)
            print(f"  Saved: {dst_p.name}")
    return model


def stage6_optuna(n_trials: int = 300):
    print(f"\n=== Stage 6: Optuna B2 ({n_trials} trials) ===")
    from optimizer.ml.optuna_search import run_optuna_search
    study = run_optuna_search(
        dataset_path=DATASET,
        results_dir=RESULTS_ORB,
        n_trials=n_trials,
        test_start="2025-07-01",
    )
    for src, dst in [
        ("best_params.json", "best_params_b2.json"),
        ("pareto_front.csv", "pareto_front_b2.csv"),
    ]:
        src_p = RESULTS_ORB / src
        dst_p = RESULTS_ORB / dst
        if src_p.exists():
            shutil.copy2(src_p, dst_p)
            print(f"  Saved: {dst_p.name}")
    return study


def stage7_robustness():
    print("\n=== Stage 7: 穩健性 B2 ===")
    from optimizer.ml.robustness import run_all_robustness_tests
    model_path = RESULTS_ORB / "orb_filter_b2.pkl"
    if not model_path.exists():
        print(f"[ERROR] {model_path} not found. Run stage 5 first.")
        return None
    result = run_all_robustness_tests(
        dataset_path=DATASET,
        results_dir=RESULTS_ORB,
        model_path=model_path,
        test_start="2025-07-01",
    )
    src = RESULTS_ORB / "robustness_report.md"
    dst = RESULTS_ORB / "robustness_report_b2.md"
    if src.exists():
        shutil.copy2(src, dst)
        print(f"  Saved: {dst.name}")
    return result


def _print_summary():
    print("\n=== B2 Pipeline Done ===")
    print(f"Artifacts in: {RESULTS_ORB}")
    expected = [
        "orb_filter_b2.pkl",
        "selected_features_b2.txt",
        "best_params_b2.json",
        "robustness_report_b2.md",
    ]
    for f in expected:
        p = RESULTS_ORB / f
        status = "✓" if p.exists() else "✗ MISSING"
        size   = f"({p.stat().st_size:,} bytes)" if p.exists() else ""
        print(f"  {status}  {f} {size}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="B2 ORB ML Pipeline — Stages 5→7")
    parser.add_argument("--from-stage", type=int, default=5,
                        help="Start from this stage (5, 6, or 7)")
    parser.add_argument("--trials", type=int, default=300,
                        help="Number of Optuna trials for stage 6 (default: 300)")
    args = parser.parse_args()

    if not DATASET.exists():
        print(f"[ERROR] Dataset not found: {DATASET}")
        print("        Run `python optimizer/ml/labels_orb.py` first.")
        sys.exit(1)

    if args.from_stage <= 5:
        stage5_train()
    if args.from_stage <= 6:
        stage6_optuna(args.trials)
    if args.from_stage <= 7:
        stage7_robustness()

    _print_summary()
